stages:
  - build
  - deploy-back
  - deploy

build_backend_develop:
  stage: build
  script:
    - cd backend
    - mvn package -DskipTests
  artifacts:
    paths:
      - $BACKEND_PATH/target/
    expire_in: 1 hour
#  only:
#    changes:
#      - backend/**/*

build_webapp_develop:
  stage: build
  script:
    - cd webapp
    - yarn install
    - yarn build
  artifacts:
    paths:
      - $WEBAPP_PATH/build/
    expire_in: 1 hour
#  only:
#    changes:
#      - webapp/**/*

deploy_backend_develop:
  stage: deploy-back
  script:
    - cd backend
    - rm -R /home/gitlab-runner/app/Acrobatt/backend/
    - mkdir /home/gitlab-runner/app/Acrobatt/backend/
    - cp -R target/* /home/gitlab-runner/app/Acrobatt/backend
  artifacts:
    expire_in: 1 hour
#  only:
#    changes:
#      - backend/**/*

deploy_webapp_develop:
  stage: deploy
  script:
    - cd webapp
    - rm -R /home/gitlab-runner/app/Acrobatt/webapp/
    - mkdir /home/gitlab-runner/app/Acrobatt/webapp/
    - cp -R build/* /home/gitlab-runner/app/Acrobatt/webapp
  artifacts:
    expire_in: 1 hour
#  only:
#    changes:
#      - webapp/**/*
