# spring.datasource.url=jdbc:h2:mem:testdb
# jdbc:mysql://localhost:3306/user_db
# jdbc:mariadb://localhost:3306/acrobatt
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
