# spring.datasource.url=jdbc:h2:mem:testdb
# jdbc:mysql://localhost:3306/user_db
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    username: root
    password: null    

  h2:
    console:
      enabled: true
      
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false